# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='venta',
        ),
        migrations.RenameField(
            model_name='caja',
            old_name='fecha_entrada',
            new_name='fecha_apertura',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
