# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresos',
            name='estado',
            field=models.CharField(blank=True, choices=[('estado_pendiente', 'Pendiente'), ('estado_aprovado', 'Aprovado'), ('estado_denegado', 'Denegado')], default='estado_pendiente', max_length=50, null=True),
        ),
    ]
