# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 22:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caja', '0002_auto_20170425_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresos',
            name='aprovado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='egresos_requests_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
