# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_auto_20170209_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
