# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_auto_20170426_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresos',
            name='cobrado',
            field=models.BooleanField(default=False),
        ),
    ]
