# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_auto_20170209_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=7)),
                ('fecha_creacion', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
        ),
    ]
