# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_capital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
