# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_auto_20170210_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='fecha_actualizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
