# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0007_auto_20170210_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capital',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
