# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0008_auto_20170210_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresos',
            name='fecha_egreso',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
