# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0009_auto_20170212_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='caja',
            name='fecha_apertura',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
