# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ajuste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('direccion', models.TextField(max_length=100)),
                ('telefono', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('simbolo_moneda', models.CharField(default='C$', max_length=10)),
                ('ruc', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_factura', models.CharField(choices=[('ticket', 'Ticket'), ('pagina', 'Página')], default='ticket', max_length=15)),
            ],
        ),
    ]
