# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajustes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajuste',
            name='api_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ajuste',
            name='api_url',
            field=models.CharField(default='https://adm-api.herokuapp.com', max_length=150),
        ),
    ]
