# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 18:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaitems',
            name='factura',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='FacturaItems',
        ),
    ]
