# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_auto_20170223_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_cobro',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
