# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_factura_fecha_cobro'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='contado',
            field=models.BooleanField(default=True),
        ),
    ]
