# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0005_factura_fecha_limite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='cobrada',
            new_name='cerrada',
        ),
        migrations.AddField(
            model_name='factura',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
    ]
