# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0006_facturaarticulos_facturaservicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaarticulos',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='facturaservicios',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
