# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 04:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0006_auto_20170503_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_abono', models.DateField(default=django.utils.timezone.now)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.Abono')),
            ],
        ),
        migrations.RemoveField(
            model_name='factura',
            name='cerrada',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='contado',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='pagada',
        ),
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('cerrado', 'Cerrado'), ('abierto', 'Abierto')], default='abierto', max_length=15),
        ),
        migrations.AddField(
            model_name='factura',
            name='pago',
            field=models.CharField(choices=[('contado', 'Contado'), ('credito', 'Credito')], default='contado', max_length=15),
        ),
    ]
