# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0008_auto_20170515_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='estado',
            new_name='abierto',
        ),
    ]
