# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
