# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_inventario_minimo_existencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='cantidad_inicial',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulos',
            name='codigo',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulos',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulos',
            name='precio_venta2',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulos',
            name='precio_venta3',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventario',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
