# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='valoracion',
            field=models.CharField(blank=True, choices=[('Excelente', 'excelente'), ('Muy bueno', 'muy_bueno'), ('Bueno', 'bueno'), ('Regular', 'regular'), ('Deficiente', 'deficiente'), ('Malo', 'malo'), ('Muy malo', 'muy_malo')], default='', max_length=50, null=True),
        ),
    ]
