# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20170503_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='sale_price2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='articulos',
            name='sale_price3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
