# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocks', models.IntegerField()),
                ('min_stocks', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sale_price2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('sale_price3', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('initial_ammount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('direction', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('phone2', models.CharField(max_length=30)),
                ('assessment', models.CharField(blank=True, choices=[('Excelente', 'excelente'), ('Muy bueno', 'muy_bueno'), ('Bueno', 'bueno'), ('Regular', 'regular'), ('Deficiente', 'deficiente'), ('Malo', 'malo'), ('Muy malo', 'muy_malo')], default='', max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product'),
        ),
    ]
