# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('direction', models.TextField(max_length=100)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('simbolo_moneda', models.CharField(default='C$', max_length=10)),
                ('ruc', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_factura', models.CharField(choices=[('ticket', 'Ticket'), ('pagina', 'Página')], default='ticket', max_length=15)),
                ('api_url', models.CharField(default='https://adm-api.herokuapp.com', max_length=150)),
                ('api_key', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
