# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha_factura', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(max_length=150),
        ),
        migrations.AddField(
            model_name='servicio',
            name='factura',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='servicios.FacturaServicio'),
        ),
    ]
