# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20170208_0521'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Articulos'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='articulos_cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
