# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20170213_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.FacturaServicio'),
        ),
    ]
