# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_auto_20170213_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaservicio',
            name='cliente_string',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='facturaservicio',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
