# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_auto_20170213_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaservicio',
            name='cliente',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente'),
        ),
        migrations.AlterField(
            model_name='facturaservicio',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
