# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_auto_20170216_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
