# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_auto_20170213_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaservicio',
            name='cliente',
        ),
    ]
