# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_auto_20170302_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervicio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
