# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_auto_20170213_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaservicio',
            name='cliente_string',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
