# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_tiposervicio_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervicio',
            name='codigo',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
