# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_auto_20170213_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='factura',
        ),
        migrations.DeleteModel(
            name='FacturaServicio',
        ),
    ]
