# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 05:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(default='000-000000-00000', max_length=16)),
                ('telefono', models.CharField(max_length=16)),
                ('puesto', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=150)),
                ('foto', models.ImageField(default='media/user.png', upload_to='media/')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
