# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(default='-', max_length=150),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='puesto',
            field=models.CharField(default='Empleado', max_length=50),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(default='+000-0000-0000', max_length=16),
        ),
    ]
