# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
