# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0003_auto_20170327_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fecha_entrada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
